services:
  web:               # Flask + Gunicorn
    build: .
    container_name: myapp_web
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /srv/osk/static:/app/static
    env_file:
      - .env