services:
  web:               # Flask + Gunicorn
    build: .
    container_name: myapp_web
    restart: unless-stopped
    expose:
      - "8000"

  nginx:
    image: nginx:1.29
    container_name: myapp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  certs: